version: '3.8'

services:
  application_bot:
    build: .
    container_name: application_bot
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=superadmin
      - MONGO_PASSWORD=130456619023
    networks:
      - shared_network
    restart: always

networks:
  shared_network:
    external: true